version: "3.9"
services:
  backend:
    build: ./backend
    container_name: usos-backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    command: /start-reload.sh
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - "db"
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # expose: # doesn't allow external db access
    #  - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - ./frontend/:/home/app
      - ./backend/dist:/home/backend/dist
      - node_modules:/home/app/node_modules
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  node_modules:
